_bankapp/_site/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account_app.urls')),
    path('accounts/', include('login_app.urls')),
]

_bankapp/_site/login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/',
         views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form,
         name='password_reset_form'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

_bankapp/account_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "account_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('completed_accounts/', views.completed_accounts,
         name='completed_accounts'),
    path('account_details/', views.account_details, name='account_details'),
    path('account_deposit/', views.account_deposit, name='account_deposit'),
    path('account_withdraw/', views.account_withdraw, name='account_withdraw'),
    path('account_transfer/', views.account_transfer, name='account_transfer'),
]

_bankapp/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account_app.urls')),
    path('accounts/', include('login_app.urls')),
]

_bankapp/login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/',
         views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form,
         name='password_reset_form'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

_bankapp/_site/login_app/models.py
from secrets import token_urlsafe
from django.db import models
from django.contrib.auth.models import User


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp}'


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    telephone_number = models.IntegerField(default=12345678)
    RANKS = (
        ('Basic', 'Basic'),
        ('Silver', 'Silver'),
        ('Gold', 'Gold'),
    )
    user_rank = models.CharField(
        choices=RANKS, default='Basic', max_length=250)

    def __str__(self):
        return f'{self.user}'

_bankapp/login_app/models.py
from secrets import token_urlsafe
from django.db import models
from django.contrib.auth.models import User


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp}'


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    telephone_number = models.IntegerField(default=12345678)
    RANKS = (
        ('Basic', 'Basic'),
        ('Silver', 'Silver'),
        ('Gold', 'Gold'),
    )
    user_rank = models.CharField(
        choices=RANKS, default='Basic', max_length=250)

    def __str__(self):
        return f'{self.user}'

_bankapp/_site/login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import UserProfile
from . import models


def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('account_app:index'))
        else:
            context = {'error': 'Bad username or password.'}
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret',
                      args=[f'{reset_request.secret}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {
            'message': 'Please click the link in the email we sent to you.'}

    return render(request, 'login_app/password_reset.html', context)


def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/password_reset_form.html', context)


def password_reset_form(request):
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    secret = request.POST['secret']

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(
        user=user, secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse('login_app:login'))
    context = {
        'error': 'Something went wrong, try again, don\'t screw up this time!'}
    return render(request, 'login_app/password_reset_form.html', context)


def sign_up(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user - try somethig else.'}
        else:
            context = {'error': 'Passwords do not match.'}
    return render(request, 'login_app/sign_up.html', context)


def user_profile(request):
    userProfiles = UserProfile.objects.filter(user=request.user)
    context = {
        'userProfiles': userProfiles,
    }
    return render(request, 'login_app/user_profile.html', context)


def delete_account(request):
    pass

_bankapp/login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . import models
from .models import UserProfile


def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('account_app:index'))
        else:
            context = {'error': 'Bad username or password.'}
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret',
                      args=[f'{reset_request.secret}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {
            'message': 'Please click the link in the email we sent to you.'}

    return render(request, 'login_app/password_reset.html', context)


def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/password_reset_form.html', context)


def password_reset_form(request):
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    secret = request.POST['secret']

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(
        user=user, secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse('login_app:login'))
    context = {
        'error': 'Something went wrong, try again, don\'t screw up this time!'}
    return render(request, 'login_app/password_reset_form.html', context)


def sign_up(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user - try somethig else.'}
        else:
            context = {'error': 'Passwords do not match.'}
    return render(request, 'login_app/sign_up.html', context)


def user_profile(request):
    userProfiles = UserProfile.objects.filter(user=request.user)
    context = {
        'userProfiles': userProfiles,
    }
    return render(request, 'login_app/user_profile.html', context)


def delete_account(request):
    pass

_bankapp/_site/login_app/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'login_app/style.css' %}"
      media="screen"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="topnav"> 
      {% if user.is_authenticated and user.is_staff %}
      <a class="btn" href="{% url 'account_app:index' %}">Home</a>
      {% else %}
      <a class="btn" href="{% url 'login_app:login' %}">Home</a>
        <a class="btn" href="{% url 'login_app:sign_up' %}">Sign up</a>
        {% endif %}

            {% if user.is_authenticated %}
            <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
            {% else %}
            <a class="nav-link2" href="{% url 'login_app:login' %}">Log in <span data-feather="log-in"></a>
            {% endif %}
      </nav>
  
    {% block content %} {% endblock %} {% block footer %} {% endblock %}
  </body>
</html>

_bankapp/_site/login_app/templates/login_app/login.html
{% extends 'login_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
    <section class="login">
    
    <a href="{% url 'login_app:password_reset' %}">Reset Password</a>
    <hr />
    <form action="{% url 'login_app:login' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username" />
      <br />
      <input type="password" name="password" placeholder="Password" />
      <br />
      <input type="submit" value="Login" />
    </form>
    <hr />
  </section>
    {% if error %}
    <p style="color: red">{{ error }}</p>
    {% endif %}
  </body>
  {% endblock %}

_bankapp/_site/login_app/templates/login_app/password_reset.html
{% extends 'login_app/base.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}
    <h1>Password Reset</h1>
    <section class="password">
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr />
    <form action="{% url 'login_app:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="email" name="email" placeholder="Email" />
      <input type="submit" value="Reset Password" />
    </form>
    <hr />
  </section>
    {% if message %}{{ message }}{% endif %}
  </body>
  {% endblock %}

_bankapp/_site/login_app/templates/login_app/password_reset_form.html
{% extends 'login_app/base.html' %}

{% block title %}Password reset {% endblock %}

{% block content %}
    <h1>New Password</h1>
    <hr />
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
      {% csrf_token %}
      <input type="email" name="email" placeholder="Email Address" />
      <input type="password" name="password" placeholder="Password" />
      <input
        type="password"
        name="confirm_password"
        placeholder="Confirm Password"
      />
      <input type="hidden" name="secret" value="{{ secret }}" />
      <input type="submit" value="Set New Password" />
    </form>
    <hr />
    {% if error %}{{ error }}{% endif %}
  </body>
  {% endblock %}

_bankapp/_site/login_app/templates/login_app/sign_up.html
{% extends 'login_app/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <h1>Sign Up</h1>
    <section class="signup">
    <hr />
    <form action="{% url 'login_app:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name" />
      <input type="password" name="password" placeholder="Password" />
      <input
        type="password"
        name="confirm_password"
        placeholder="Confirm Password"
      />
      <input type="email" name="email" placeholder="Email Address" />
      <input
        type="phone"
        name="telephone_number"
        placeholder="Telephone number"
      />
      <input type="submit" value="Sign Up" />
    </form>
  </section>
  </body>

  {% endblock %}

_bankapp/_site/login_app/templates/login_app/user_profile.html
{% extends 'login_app/base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}

    <h1>User profile</h1>
    Hello, {{ user.username }}.

    <form method="POST">
      {% csrf_token %}
      <input type="hidden" name="username" value="{{user.username}}" />
    </form>
    {% for userProfile in userProfiles %}
    <ul class="user-list">
      <li>User phone number:</li>
      {{ userProfile.telephone_number }}
      <li>Your Ranking is:</li>
      {{ userProfile.user_rank }}
    </ul>
    {% endfor %}
  </body>
  {% endblock %}