_bankapp/_site/account_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "account_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('completed_accounts/', views.completed_accounts,
         name='completed_accounts'),
    path('account_details/', views.account_details, name='account_details'),
    path('account_deposit/', views.account_deposit, name='account_deposit'),
    path('account_withdraw/', views.account_withdraw, name='account_withdraw'),
    path('account_transfer/', views.account_transfer, name='account_transfer'),
]

_bankapp/account_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "account_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('completed_accounts/', views.completed_accounts,
         name='completed_accounts'),
    path('account_details/', views.account_details, name='account_details'),
    path('account_deposit/', views.account_deposit, name='account_deposit'),
    path('account_withdraw/', views.account_withdraw, name='account_withdraw'),
    path('account_transfer/', views.account_transfer, name='account_transfer'),
]

_bankapp/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account_app.urls')),
    path('accounts/', include('login_app.urls')),
]

_bankapp/login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/',
         views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form,
         name='password_reset_form'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

_bankapp/_site/account_app/models.py
import random
from django.contrib.auth.models import User
from django.db import models


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    number = models.IntegerField(default=0)
    balance = models.IntegerField(default=0)

    @classmethod
    def create(cls, user, text, number, balance):
        account = cls()
        account.user = user
        account.text = text
        account.number = number
        account.balance = balance
        account.save()

    @classmethod
    def withdraw(cls, number, amount):
        transaction_id = random.randint(100000, 400000)
        account = Account.objects.get(number=number)
        account.balance = account.balance - amount
        account.save()

        # CREATE account TRANSACTION WITH NEW TRANSACTION ID
        Account_Transaction.create(account.user, account.number,
                                   account.balance, transaction_id, "withdraw", amount)

    @classmethod
    def deposit(cls, number, amount):
        transaction_id = random.randint(100000, 400000)
        account = Account.objects.get(number=number)
        account.balance = account.balance + amount
        account.save()

        # CREATE account TRANSACTION WITH NEW TRANSACTION ID
        Account_Transaction.create(account.user, account.number,
                                   account.balance, transaction_id, "deposit", amount)

    def toggle_status(self):
        # self.text = not self.text
        self.save()

    def __str__(self):
        return f"Account: {self.number} User: {self.user}"


class Account_Transaction(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    number = models.IntegerField(null=False)
    balance = models.IntegerField(null=False)
    transaction_id = models.IntegerField(default=0)
    transaction_type = models.CharField(default="Not Stated", max_length=250)
    transaction_amount = models.IntegerField(default=0, null=False)

    @classmethod
    def create(cls, user, number, balance, transaction_id, transaction_type, transaction_amount):
        account_transaction = cls()
        account_transaction.user = user
        account_transaction.number = number
        account_transaction.balance = balance
        account_transaction.transaction_id = transaction_id
        account_transaction.transaction_type = transaction_type
        account_transaction.transaction_amount = transaction_amount
        account_transaction.save()

    def __str__(self):
        return f"Transaction ID: {self.transaction_id} Account Number: {self.number} User: {self.user}"

_bankapp/account_app/models.py
import random
from django.contrib.auth.models import User
from django.db import models


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    number = models.IntegerField(default=0)
    balance = models.IntegerField(default=0)

    @classmethod
    def create(cls, user, text, number, balance):
        account = cls()
        account.user = user
        account.text = text
        account.number = number
        account.balance = balance
        account.save()

    @classmethod
    def withdraw(cls, number, amount):
        transaction_id = random.randint(100000, 400000)
        account = Account.objects.get(number=number)
        account.balance = account.balance - amount
        account.save()

        # CREATE account TRANSACTION WITH NEW TRANSACTION ID
        Account_Transaction.create(account.user, account.number,
                                   account.balance, transaction_id, "withdraw", amount)

    @classmethod
    def deposit(cls, number, amount):
        transaction_id = random.randint(100000, 400000)
        account = Account.objects.get(number=number)
        account.balance = account.balance + amount
        account.save()

        # CREATE account TRANSACTION WITH NEW TRANSACTION ID
        Account_Transaction.create(account.user, account.number,
                                   account.balance, transaction_id, "deposit", amount)

    def toggle_status(self):
        # self.text = not self.text
        self.save()

    def __str__(self):
        return f"Account: {self.number} User: {self.user}"


class Account_Transaction(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    number = models.IntegerField(null=False)
    balance = models.IntegerField(null=False)
    transaction_id = models.IntegerField(default=0)
    transaction_type = models.CharField(default="Not Stated", max_length=250)
    transaction_amount = models.IntegerField(default=0, null=False)

    @classmethod
    def create(cls, user, number, balance, transaction_id, transaction_type, transaction_amount):
        account_transaction = cls()
        account_transaction.user = user
        account_transaction.number = number
        account_transaction.balance = balance
        account_transaction.transaction_id = transaction_id
        account_transaction.transaction_type = transaction_type
        account_transaction.transaction_amount = transaction_amount
        account_transaction.save()

    def __str__(self):
        return f"Transaction ID: {self.transaction_id} Account Number: {self.number} User: {self.user}"

_bankapp/_site/account_app/views.py
import random
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from login_app.models import UserProfile
from .models import Account, Account_Transaction

# Create your views here.


@login_required
def index(request):
    if request.method == 'POST':
        uuid = random.randint(100000, 199999)

        Account.create(
            request.user, request.POST['account_name'], uuid, request.POST['starting_balance'])

        transaction_id = random.randint(100000, 199999)

        transactionAmount = request.POST['starting_balance']

        Account_Transaction.create(
            request.user, uuid, request.POST['starting_balance'], transaction_id, "Initial Deposit", transactionAmount)

    #accounts = Account.objects.filter(status=False).filter(user=request.user)
    accounts = Account.objects.filter(user=request.user)

    userProfiles = UserProfile.objects.filter(user=request.user)

    context = {
        'accounts': accounts,
        'userProfiles': userProfiles,
    }
    return render(request, 'account_app/index.html', context)


@login_required
def completed_accounts(request):
    accounts = Account.objects.filter(status=True)
    context = {
        'accounts': accounts,
    }
    return render(request, 'account_app/completed_accounts.html', context)


@login_required
def account_details(request):
    account_number = request.POST['account_number']
    accounts = Account.objects.filter(number=account_number)

    accountTransactions = Account_Transaction.objects.filter(
        number=account_number)

    context = {
        'accounts': accounts,
        'accountTransactions': accountTransactions,
    }

    return render(request, 'account_app/account_details.html', context)


@login_required
def account_withdraw(request):
    # Account.withdraw(request.POST['account_number'], request.POST['withdraw_amount'])
    # NO LONGER USING ABOVE FUNCTION, WILL RATHER IMPLEMENT THE FUNCTION HERE.

    transaction_id = random.randint(100000, 200000)
    account_number = request.POST['account_number']
    account = Account.objects.get(number=account_number)

    account.balance = account.balance - int(request.POST['withdraw_amount'])
    account.save()

    transactionAmount = request.POST['withdraw_amount']

    # CREATE Account TRANSACTION WITH NEW TRANSACTION ID
    Account_Transaction.create(account.user, account.number,
                               account.balance, transaction_id, "Withdraw", transactionAmount)

    accounts = Account.objects.filter(number=account_number)
    accountTransactions = Account_Transaction.objects.filter(
        number=account_number)

    context = {
        'accounts': accounts,
        'accountTransactions': accountTransactions,
    }

    return render(request, 'account_app/account_details.html', context)


@login_required
def account_deposit(request):
    # Account.deposit(request.POST['account_number'], request.POST['deposit_amount'])
    # NO LONGER USING ABOVE FUNCTION, WILL RATHER IMPLEMENT THE FUNCTION HERE.
    transaction_id = random.randint(100000, 200000)

    account_number = request.POST['account_number']
    account = Account.objects.get(number=account_number)
    account.balance = account.balance + int(request.POST['deposit_amount'])
    account.save()

    transactionAmount = request.POST['deposit_amount']

    # CREATE Account TRANSACTION WITH NEW TRANSACTION ID
    Account_Transaction.create(account.user, account.number,
                               account.balance, transaction_id, "Deposit", transactionAmount)

    accounts = Account.objects.filter(number=account_number)
    accountTransactions = Account_Transaction.objects.filter(
        number=account_number)

    context = {
        'accounts': accounts,
        'accountTransactions': accountTransactions,
    }

    return render(request, 'account_app/account_details.html', context)


@login_required
def account_transfer(request):
    fromAccountNumber = request.POST['transfer_from_account']
    toAccountNumber = request.POST['transfer_to_account']

    fromAccount = Account.objects.get(number=fromAccountNumber)
    toAccount = Account.objects.get(number=toAccountNumber)

    transferAmount = request.POST['transfer_amount']

    fromAccount.balance = fromAccount.balance - int(transferAmount)
    toAccount.balance = toAccount.balance + int(transferAmount)

    fromAccount.save()
    toAccount.save()

    # CREATE Account TRANSACTION WITH NEW TRANSACTION ID
    transaction_id = random.randint(100000, 200000)

    Account_Transaction.create(fromAccount.user, fromAccount.number,
                               fromAccount.balance, transaction_id, "Transfer Out", transferAmount)

    Account_Transaction.create(toAccount.user, toAccount.number,
                               toAccount.balance, transaction_id, "Transfer In", transferAmount)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

_bankapp/account_app/views.py
import random
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from login_app.models import UserProfile
from .models import Account, Account_Transaction

# Create your views here.


@login_required
def index(request):
    if request.method == 'POST':
        uuid = random.randint(100000, 199999)

        Account.create(
            request.user, request.POST['account_name'], uuid, request.POST['starting_balance'])

        transaction_id = random.randint(100000, 199999)

        transactionAmount = request.POST['starting_balance']

        Account_Transaction.create(
            request.user, uuid, request.POST['starting_balance'], transaction_id, "Initial Deposit", transactionAmount)

    #accounts = Account.objects.filter(status=False).filter(user=request.user)
    accounts = Account.objects.filter(user=request.user)

    userProfiles = UserProfile.objects.filter(user=request.user)

    context = {
        'accounts': accounts,
        'userProfiles': userProfiles,
    }
    return render(request, 'account_app/index.html', context)


@login_required
def completed_accounts(request):
    accounts = Account.objects.filter(status=True)
    context = {
        'accounts': accounts,
    }
    return render(request, 'account_app/completed_accounts.html', context)


@login_required
def account_details(request):
    account_number = request.POST['account_number']
    accounts = Account.objects.filter(number=account_number)

    accountTransactions = Account_Transaction.objects.filter(
        number=account_number)

    context = {
        'accounts': accounts,
        'accountTransactions': accountTransactions,
    }

    return render(request, 'account_app/account_details.html', context)


@login_required
def account_withdraw(request):
    # Account.withdraw(request.POST['account_number'], request.POST['withdraw_amount'])
    # NO LONGER USING ABOVE FUNCTION, WILL RATHER IMPLEMENT THE FUNCTION HERE.

    transaction_id = random.randint(100000, 200000)
    account_number = request.POST['account_number']
    account = Account.objects.get(number=account_number)

    account.balance = account.balance - int(request.POST['withdraw_amount'])
    account.save()

    transactionAmount = request.POST['withdraw_amount']

    # CREATE Account TRANSACTION WITH NEW TRANSACTION ID
    Account_Transaction.create(account.user, account.number,
                               account.balance, transaction_id, "Withdraw", transactionAmount)

    accounts = Account.objects.filter(number=account_number)
    account_transaction = Account_Transaction.objects.filter(
        number=account_number)

    context = {
        'accounts': accounts,
        'account_transaction': account_transaction,
    }

    return render(request, 'account_app/account_details.html', context)


@login_required
def account_deposit(request):
    # Account.deposit(request.POST['account_number'], request.POST['deposit_amount'])
    # NO LONGER USING ABOVE FUNCTION, WILL RATHER IMPLEMENT THE FUNCTION HERE.
    transaction_id = random.randint(100000, 200000)

    account_number = request.POST['account_number']
    account = Account.objects.get(number=account_number)
    account.balance = account.balance + int(request.POST['deposit_amount'])
    account.save()

    transactionAmount = request.POST['deposit_amount']

    # CREATE Account TRANSACTION WITH NEW TRANSACTION ID
    Account_Transaction.create(account.user, account.number,
                               account.balance, transaction_id, "Deposit", transactionAmount)

    accounts = Account.objects.filter(number=account_number)
    accountTransactions = Account_Transaction.objects.filter(
        number=account_number)

    context = {
        'accounts': accounts,
        'accountTransactions': accountTransactions,
    }

    return render(request, 'account_app/account_details.html', context)


@login_required
def account_transfer(request):
    from_account_number = request.POST['transfer_from_account']
    to_account_number = request.POST['transfer_to_account']

    from_account = Account.objects.get(number=from_account_number)
    to_account = Account.objects.get(number=to_account_number)

    transfer_amounts = request.POST['transfer_amount']

    from_account.balance = from_account.balance - int(transfer_amounts)
    to_account.balance = to_account.balance + int(transfer_amounts)

    from_account.save()
    to_account.save()

    # CREATE Account TRANSACTION WITH NEW TRANSACTION ID
    transaction_id = random.randint(100000, 200000)

    Account_Transaction.create(from_account.user, from_account.number,
                               from_account.balance, transaction_id, "Transfer Out", transfer_amounts)

    Account_Transaction.create(to_account.user, to_account.number,
                               to_account.balance, transaction_id, "Transfer In", transfer_amounts)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

_bankapp/account_app/templates/account_app/account_details copy.html
<h1>Completed Banks</h1>
<a href="{% url 'account_app:index' %}">Home</a>
<hr />
<ul>
  {% for bank in banks %}
  <li>
    <form action="." method="POST">
      {% csrf_token %}
      <input
        type="checkbox"
        name="status"
        {%
        if
        bank.status
        %}checked{%
        endif
        %}
      />
      <input type="submit" value="Update" />
      {{ bank.text }}
      <input type="hidden" name="pk" value="{{bank.pk}}" />
    </form>
  </li>
  {% endfor %}
</ul>
<hr />
{% endblock %}

_bankapp/account_app/templates/account_app/account_details.html
{% extends 'account_app/base.html' %} {% block title %}Account{% endblock %}
{% block content %}
<div class="accounts_text"><h1>Account details</h1></div>
<div class="transactions-text"><h1>Transactions</h1></div>
<section class="account-details">
<a href="{% url 'account_app:index' %}">Home</a>
<hr />
<ul>
  {% for account in accounts %}

  <ul class="account-list">
    Account Name:
    {{ account.text }}
    Account number:
    {{ account.number }}
    Your Balance
    {{ account.balance }}
  </ul>


  <form action="{% url 'account_app:account_withdraw' %}" method="POST">
    {% csrf_token %}
    <p>Withdraw</p>
    <input type="hidden" name="account_number" value="{{account.number}}" />
    <input type="number" placeholder="Amount" name="withdraw_amount" required max="{{account.balance}}"/>
    <input type="submit" value="Withdraw" />
  </form>

  <form action="{% url 'account_app:account_deposit' %}" method="POST">
    {% csrf_token %}
    <p>Deposit</p>
    <input type="hidden" name="account_number" value="{{account.number}}" />
    <input type="number" placeholder="Amount" name="deposit_amount" required min="1"/>
    <input type="submit" value="Deposit" />
  </form>
</section>
  <style>
    .account-list {
      display: grid;
      grid-template-columns: repeat(8, 1fr);
      grid-column-gap: 25px;
      margin-top: 10px;
      margin-bottom: 10px;
    }
  </style>
  {% endfor %}
</ul>

<div class="account-log">

{% for accountTransaction in accountTransactions %}

<div class="transaction-table">
  <div><b>Transaction ID</b></div>
  <div><b>Transaction Type</b></div>
  <div><b>Amount</b></div>
  <div><b>Balance</b></div>
  <div>{{ accountTransaction.transactionID }}</div>

  <div>{{ accountTransaction.transactionType }}</div>
  {% if accountTransaction.transactionType == "Withdraw" %}
    <div style="color:red;">- {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Transfer Out"%}
    <div style="color:red;">- {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Deposit" %}
    <div style="color:green;">+ {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Transfer In" %}
    <div style="color:green;">+ {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Initial Deposit" %}
    <div style="color:green;">+ {{ accountTransaction.transactionAmount }}</div>
  {% endif %}

  <div>{{ accountTransaction.balance }}</div>

</div>
</div>
<style>
  .transaction-table {
    display:grid;
    grid-template-columns:1fr 1fr 1fr 1fr;
    margin-bottom:10px;
  }
</style>
{% endfor %}
{% endblock %}

_bankapp/account_app/templates/account_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'account_app/style.css' %}"
      media="screen"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="topnav"> 
      <br />
      {% if user.is_authenticated and user.is_staff %}
      <a class="btn" href="{% url 'account_app:index' %}">Home</a>
      {% else %}
      <a class="btn" href="{% url 'login_app:login' %}">Home</a>
        <a class="btn" href="{% url 'login_app:sign_up' %}">Sign up</a>
        {% endif %}

            {% if user.is_authenticated %}
            <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
            {% else %}
            <a class="nav-link2" href="{% url 'login_app:login' %}">Log in <span data-feather="log-in"></a>
            {% endif %}
          </li>
        </ul>
        <div class="hello_username">Hi, {{ user.username }}. </div>
      </nav>
  
    {% block content %} {% endblock %} {% block footer %} {% endblock %}
  </body>
</html>

_bankapp/account_app/templates/account_app/index.html
{% extends 'account_app/base.html' %} {% block title %}Accounts{% endblock %}
{% block content %}
<div class="accounts_text"><h1>Accounts</h1></div>
<div class="transfer_text"><h1>Transfer Money</h1></div>
<section class="account">
<a href="{% url 'login_app:user_profile' %}">View Profile Details</a>

{% for userProfile in userProfiles %}
<div>
  <p>Your current ranking is {{ userProfile.user_rank }}.<br>
  {% if userProfile.user_rank == "Basic" %} Loan Status (BASIC): You cannot take a loan. 
  {% elif userProfile.user_rank == "Silver" %} Loan Status (SILVER): You can take a loan of up to
  $500.</p>
   <button class="pink-btn"><a href="">Take A Loan</a> </button>
  {% elif userProfile.user_rank == "Gold" %} Loan Status
  (GOLD): You can take a loan of up to $1500. <a href="">Take A Loan</a>
  {% endif %}
</div>
{% endfor %}
<hr />

<!-- LIST ACCOUNTS -->

<h2>Your Accounts</h2>

  {% for account in accounts %}
  
    <form action="{% url 'account_app:account_details' %}" method="POST">
      {% csrf_token %}
      
      <ul class="account-list">
        Account Name:
        {{ account.text }}<br>
        Account number:
        {{ account.number }} <br>
        Your Balance
        {{ account.balance }}<br><br>
      
    <input class="view_account "type="submit" value="View Account Details" />
  </ul>
      <input type="hidden" name="account_number" value="{{account.number}}" />
    </form>
    
  {% endfor %}

<hr />


<!-- CREATE NEW ACCOUNT -->


<div class="new_account_container">
  <h2>Add new bank account</h2>
  <div class="new_account">
<form action="." method="POST">
  {% csrf_token %}
  
  <input type="text" placeholder="Account Name" name="account_name" />
  <input type="number" placeholder="Starting Balance" name="starting_balance" />
  <input type="submit" value="Add" class="pink-btn"/>

</form>
</div>
</div>

{% if accounts %}
</section>

<section class="transfer_accounts">
  <div class="tranfer1">
    <h2>From</h2>
<form action="{% url 'account_app:account_transfer' %}" method="POST" class="transfer-form">
  {% csrf_token %}
  <label for="transfer_from_account">
    <select name="transfer_from_account">
      {% for account in accounts %}
        <option value="{{ account.number }}">Account Name: {{ account.text }} | Account Number:{{ account.number }} | Balance: {{ account.balance }}</option>
      {% endfor %}
    </select>
  </label> 
  <label for="transfer_to_account"><h2>To</h2>
    <select name="transfer_to_account">
      {% for account in accounts %}
        <option value="{{ account.number }}"><b>Account Name: {{ account.text }} | Account Number:{{ account.number }} | Balance: {{ account.balance }}</option>
      {% endfor %}
    </select>
  </label>
  <br>

    <label><h2>Amount</h2>
    <input type="number" placeholder="Amount" name="transfer_amount" />
    </label>
    <input type="submit" value="Transfer" class="pink-btn" />
  </div>

</form>
</section>


{% endif %}

{% endblock %}